#!/bin/sh

if [ "$PKG_UPGRADE" != 1 ]; then
	uci get luci.themes.Material3 >/dev/null 2>&1 || {
		uci set luci.themes.Material3=/luci-static/material3
		uci set luci.main.mediaurlbase=/luci-static/material3
		uci set luci.themes.Material3Blue=/luci-static/material3-blue
		uci set luci.themes.Material3Green=/luci-static/material3-green
		uci set luci.themes.Material3Red=/luci-static/material3-red
		uci set luci.themes.Material3Amoled=/luci-static/material3-amoled
		uci commit luci
	}
fi

exit 0
